// <auto-generated />
using Altairis.Services.StaticContent.DemoApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Altairis.Services.StaticContent.DemoApp.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20220829185517_Add_DefaultContent")]
    partial class Add_DefaultContent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Altairis.Services.StaticContent.StaticContentItem", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("StaticContentItems");

                    b.HasData(
                        new
                        {
                            Key = "welcome",
                            Text = "# Welcome"
                        },
                        new
                        {
                            Key = "privacy",
                            Text = "This is my _privacy policy_."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
